databases:
  - name: victor_portfolio_backend
    databaseName: victor_portfolio_backend
    user: victor_portfolio_backend

services:
  - type: web
    name: victor_portfolio_backend
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: victor_portfolio_backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
   name: redis
   ipAllowList: []
   plan: free
   maxmemoryPolicy: noeviction    