databases:
  - name: victor_portfolio_backend
    databaseName: victor_portfolio_backend
    ipAllowList: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: victor_portfolio_backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction