default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: victor_portfolio_backend_development
  username: <%= ENV["SAMPLE_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["SAMPLE_APP_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: victor_portfolio_backend_test
  username: <%= ENV["SAMPLE_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["SAMPLE_APP_DATABASE_PASSWORD"] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: victor_portfolio_backend_production
  username: victor_portfolio_backend
  password: <%= ENV["VICTOR_PORTFOLIO_BACKEND_DATABASE_PASSWORD"] %>
